#!/bin/bash -e

cd examples/demoapp
./gradlew clean assembleDebug
cp app/build/outputs/apk/debug/app-debug.apk ../../speech-demo-debug.apk
cd ../..

./gradlew :speech:clean :speech:bintrayUpload

version=$(cat manifest.gradle | grep "library_version" | tr "'" '\n' | head -n 2 | tail -n 1)
hub release create -a speech-demo-debug.apk -m "$version" "$version"
